# Generated by Django 5.0.6 on 2024-06-20 09:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstapp', '0002_alter_accountuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('d33c104c-70a1-4b69-92e6-bffce0cba3a4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
