# Generated by Django 5.0.6 on 2024-06-22 11:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstapp', '0003_alter_accountuser_account_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('10b7424a-e91c-48d2-b80c-e8392f7bbe4d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
