# Generated by Django 5.0.6 on 2024-06-22 22:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstapp', '0004_alter_accountuser_account_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='account_user_email',
            field=models.CharField(default='default@example.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('8941cdff-76f9-46ed-bcf5-cf3601b15a91'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
