# Generated by Django 5.0.6 on 2024-06-22 23:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstapp', '0005_accountuser_account_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('08964d17-4a5d-41ea-aeca-1c30ae5fdf8a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
