# Generated by Django 5.0.6 on 2024-06-23 05:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstapp', '0006_alter_accountuser_account_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_fullname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('c907564d-c47f-4c45-bddd-6ec5bf940eb4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
