# Generated by Django 5.0.6 on 2024-06-23 06:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstapp', '0008_alter_accountuser_account_user_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_fullname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('06c65193-bee2-4c38-9ce7-9d9ae8ab6fa3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
