# Generated by Django 5.0.6 on 2024-06-23 12:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstapp', '0010_alter_accountuser_account_user_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('1a80810f-af85-48c4-915e-38c993134694'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
