# Generated by Django 5.0.6 on 2024-06-25 12:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstapp', '0011_alter_accountuser_account_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('79844615-6a71-40e7-8e17-212deb39b6b4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
