# Generated by Django 5.0.6 on 2024-06-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstapp', '0013_alter_accountuser_account_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_fullname',
            field=models.CharField(max_length=255),
        ),
    ]
