# Generated by Django 5.0.6 on 2024-06-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstapp', '0014_alter_accountuser_account_user_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_email',
            field=models.EmailField(default='default@example.com', max_length=255),
        ),
    ]
