# Generated by Django 5.0.6 on 2024-06-25 13:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstapp', '0015_alter_accountuser_account_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_email',
            field=models.CharField(default='default@example.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_fullname',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('376700a6-dde5-4607-869c-996568010fb6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_updated_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
