# Generated by Django 5.0.6 on 2024-06-25 13:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstapp', '0016_alter_accountuser_account_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('45ed3575-9903-4b18-8698-1c249afdd402'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
