# Generated by Django 5.0.6 on 2024-06-25 13:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstapp', '0017_alter_accountuser_account_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('9f65e1c8-8ee5-4091-924e-7d30a71553ea'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
