# Generated by Django 5.0.6 on 2024-06-25 13:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstapp', '0018_alter_accountuser_account_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('12c45a3e-acae-41d6-b389-ff0f00bc0758'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
