# Generated by Django 5.0.6 on 2024-06-25 13:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstapp', '0019_alter_accountuser_account_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('6d00b640-29d7-472a-92de-954e561cb25a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
