# Generated by Django 5.0.6 on 2024-06-25 14:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstapp', '0022_alter_accountuser_account_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('8152aa06-4ef4-4a23-8876-c252b84751c6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
