# Generated by Django 5.0.6 on 2024-06-25 14:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstapp', '0023_alter_accountuser_account_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('8a4346e5-98ca-4f79-8bab-23024ee51556'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
