# Generated by Django 5.0.6 on 2024-06-25 15:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstapp', '0024_alter_accountuser_account_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('4f06ac9c-d229-42fb-826e-f1d1d5e0ad4f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
